### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/api/v1/parking_slots

###
GET http://localhost:8080/api/v1/ticket/getAllTicket
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmYWlqYWFuQHRlc3QuY29tIiwiaWF0IjoxNzc1ODQ0NTg1LCJleHAiOjE3NzU4NDgxODV9.HhiJ1vHivlpJx_qzDyVt1YZTQCRiF-gFP3PYFIMSG58
###
POST http://localhost:8080/api/v1/ticket/park
Content-Type: application/json

{
  "vehicleNumber": "MH12AB2234",
  "vehicleType": "bike",
  "phoneNumber": 9020713483
}

###
PUT http://localhost:8080/api/v1/ticket/exit/2

###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "name": "Faijaan",
  "email": "faijaan@test.com",
  "password": "87654321"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "faijaan@test.com",
  "password": "87654321"
}

###
GET http://localhost:8080/api/v1/ticket/report

//Get revenue as per month and year
###
GET http://localhost:8080/api/v1/ticket/getrevenue?month=4&year=2026

//Get today's revenue
###
GET http://localhost:8080/api/v1/ticket/todayrevenue

//Get current month revenue
###
GET http://localhost:8080/api/v1/ticket/monthlyrevenue

###
GET http://localhost:8080/api/v1/ticket/verify?otp=314728&id=3