### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/api/v1/parking_slots

###
GET http://localhost:8080/api/v1/ticket

###
POST http://localhost:8080/api/v1/ticket/park
Content-Type: application/json

{
  "vehicleNumber": "MH12AB1234",
  "vehicleType": "car",
  "phoneNumber": 9020713497
}

###
PUT http://localhost:8080/api/v1/ticket/exit/101